server:
  port: 8004

spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 19871124
    driver-class-name: com.mysql.cj.jdbc.Driver